# Configuration OAuth2 pour Google en production
# IMPORTANT: Vous devez configurer https://devtechly.com/login/oauth2/code/google
# comme URI de redirection autoris√©e dans Google Cloud Console
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}
            scope: openid, profile, email
            redirect-uri: 'https://devtechly.com/login/oauth2/code/{registrationId}'
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

# Configuration pour le domaine de production
jhipster:
  mail:
    from: noreply@devtechly.com
    base-url: https://devtechly.com
